### ISSUE TITLE
'  from oauth2client.tools import run' throws exception

### ISSUE THREAD

**Issue by kongakong** [googledrive/deduper-script#3]
I have used this command ` pip install oauth2client ` to install the package.

But I am getting this error:

```
Traceback (most recent call last):
  File "dedup.py", line 13, in <module>
    from oauth2client.tools import run
ImportError: cannot import name run

```

Could the code has become outdated?

**Comment by wbowlin** [comment]
@kongakong Check out this PR. It addresses your error:

`https://github.com/googledrive/deduper-script/pull/4`

**Comment by grant** [comment]
#4 fixes this.
